import { defineConfig } from "tsup";

export default defineConfig({
  entry: {
    index: "src/index.ts",
    ids: "src/ids.ts",
    "schema/index": "src/schema/index.ts",
    "schema/v0": "src/schema/v0.ts",
    "schema/flowJunction": "src/schema/flowJunction.ts",
    "schema/files/index": "src/schema/files/index.ts",
    "schema/files/scenario": "src/schema/files/scenario.ts",
    "schema/files/comment": "src/schema/files/comment.ts",
    "schema/files/glossary": "src/schema/files/glossary.ts",
    "schema/files/knowledgeTable": "src/schema/files/knowledgeTable.ts",
    "schema/files/models": "src/schema/files/models.ts",
    "schema/files/persona": "src/schema/files/persona.ts",
    "schema/files/project": "src/schema/files/project.ts",
    "schema/files/result": "src/schema/files/result.ts",
    "schema/files/rubric": "src/schema/files/rubric.ts",
    "schema/files/testCase": "src/schema/files/testCase.ts",
    "codegen/index": "src/codegen/index.ts",
    "codegen/promptGenerator": "src/codegen/promptGenerator.ts",
    "codegen/scriptsCsv": "src/codegen/scriptsCsv.ts",
    "codegen/translationsCsv": "src/codegen/translationsCsv.ts",
    "codegen/knowledgeCsv": "src/codegen/knowledgeCsv.ts",
    "validation/index": "src/validation/index.ts",
    "validation/ajv": "src/validation/ajv.ts",
    "validation/graphRules": "src/validation/graphRules.ts",
    "validation/testingRules": "src/validation/testingRules.ts",
    "files/index": "src/files/index.ts",
    "files/github": "src/files/github.ts",
    "files/models": "src/files/models.ts",
    "files/scaffold": "src/files/scaffold.ts",
    "files/types": "src/files/types.ts",
    "files/zip": "src/files/zip.ts",
    "files/testing": "src/files/testing.ts",
    "llm/index": "src/llm/index.ts",
    "llm/dispatch": "src/llm/dispatch.ts",
    "llm/prompts": "src/llm/prompts.ts",
    "llm/types": "src/llm/types.ts",
    "llm/providers/google": "src/llm/providers/google.ts",
    "llm/providers/openai": "src/llm/providers/openai.ts",
    "llm/providers/openai-compatible": "src/llm/providers/openai-compatible.ts",
    "runtime/index": "src/runtime/index.ts",
    "runtime/eventTypes": "src/runtime/eventTypes.ts",
    "runtime/formatEvent": "src/runtime/formatEvent.ts",
    "runtime/transcript": "src/runtime/transcript.ts",
    "runtime/translate": "src/runtime/translate.ts",
    "runtime/contextVars": "src/runtime/contextVars.ts",
    "runtime/contextVarsGen": "src/runtime/contextVarsGen.ts",
    "runtime/capabilityMocks": "src/runtime/capabilityMocks.ts",
    "runtime/capabilityMocksGen": "src/runtime/capabilityMocksGen.ts",
    "runtime/scenarioRuntime": "src/runtime/scenarioRuntime.ts",
    "runtime/scenarioGen": "src/runtime/scenarioGen.ts",
    "runtime/personaGen": "src/runtime/personaGen.ts",
    "runtime/personaClient": "src/runtime/personaClient.ts",
    "runtime/promptClient": "src/runtime/promptClient.ts",
    "runtime/textClient": "src/runtime/textClient.ts",
  },
  format: ["esm", "cjs"],
  dts: true,
  sourcemap: true,
  clean: true,
});
